config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "locations#index"
  resources :locations do
    resources :comments
  end
  get "/trending", to:"locations#trending"
  get "/favorites", to:"favorites#index"
  post "/favorites/:location_id", to:"favorites#create"
  delete "/favorites/:favorite_id", to:"favorites#destroy"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :location

    validates :body, presence: true, length: { minimum: 10 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :location, counter_cache: true
    validates_uniqueness_of :location_id, :scope => :user_id

    validates :user_id, presence: true
    validates :location_id, presence: true
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :favorites, dependent: :destroy
    belongs_to :user
    has_many :comments

    CATEGORIES = { 'Restaurant': 'restaurant', 'Dessert': 'dessert', 'Group Activity': 'group activity', 'Nature': 'nature', 'Park': 'park', 'Fun': 'fun', 'Arcade': 'arcade', 'Date Night': 'date night', 'Adventure': 'adventure', 'Family': 'family', 'Movie': 'movie', 'Alternative': 'alternative'}

    validates :name, presence: true
    validates :street1, presence: true
    validates :city, presence: true
    validates :state, presence: true
    validates :zip, presence: true
    validates :categories, presence: true
end

app/models/trigram.rb
class Trigram < ActiveRecord::Base
    include Fuzzily::Model
  end

app/models/user.rb
class User < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :locations
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @location = Location.find(params[:location_id])
        @comment = @location.comments.build(comment_params)
        @comment.user_id = current_user.id
        @comment.save
        redirect_to location_path(@location)
    end
    def destroy
      @comment = current_user.comments.find(params[:id])
      if @comment
        @location = @comment.location
        @comment.destroy
        redirect_to location_path(@location)
      else
        redirect_to root_path
      end
    end
    def edit
      @comment = current_user.comments.find(params[:id])
    end 
    private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  def index
    if user_signed_in?
      @favorites = current_user.favorites
    end
  end
  def create
    @location = Location.find(params[:location_id])
    @favorite = Favorite.new(user_id: current_user.id, location_id: @location.id)

    if @favorite.save
      flash[:alert] = "#{@location.name} has been saved to favorites."
    else
      flash[:alert] = "There was an error adding #{@location.name} to favorites."
    end
    redirect_to location_path(@location)
  end
  def destroy
    favorite = Favorite.find(params[:favorite_id])
    location = favorite.location
    favorite.destroy
    flash[:alert] = "This location has been removed from favorites."
    redirect_to location_path(location)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :delete]
    def index
      @locations = Location.all
      @cat_true = false;
      @title = "Locations"

      if params.dig(:location, :categories) != nil && params[:location][:categories]
        query_string = ""
        @cat_checked = params[:location][:categories].reject(&:blank?)
        if params[:location][:categories]
          @cat_checked.each do |cat|
            query_string << "'#{cat}'=ANY(categories)" << " AND "
          end
        end
        query_string = query_string[0...-4]
        @locations = @locations.where(query_string)
        @cat_true = true
      end

      if params[:search_by_name] && params[:search_by_name] != ""
        @locations = @locations.where("name ILIKE ? or zip = ? ", "%#{params[:search_by_name]}%","#{params[:search_by_name]}")
        @cat_true = false
      end
    end
    def trending
      @locations = Location.order(favorites_count: :desc).limit(8)
      @cat_true = false
      @title = "Trending"
      
      if params.dig(:location, :categories) != nil && params[:location][:categories]
        query_string = ""
        @cat_checked = params[:location][:categories].reject(&:blank?)
        if params[:location][:categories]
          @cat_checked.each do |cat|
            query_string << "'#{cat}'=ANY(categories)" << " AND "
          end
        end
        query_string = query_string[0...-4]
        @locations = @locations.where(query_string)
        @cat_true = true
      end

      if params[:search_by_name] && params[:search_by_name] != ""
        @locations = @locations.where("name ILIKE ? or zip = ? ", "%#{params[:search_by_name]}%","#{params[:search_by_name]}")
        @cat_true = false
      end
    end
    def show
      @location = Location.find(params[:id])
      if user_signed_in?
        @favorite = Favorite.where(user_id: current_user.id, location_id: @location.id).take
      end
    end
    def new
      @location = Location.new
    end
    def create
      @location = current_user.locations.build(location_params)
      if @location.save
        redirect_to @location
      else
        render :new
      end
    end
    def destroy
      @location = Location.find(params[:id])
      @location.destroy
      flash[:alert] = "This location has been deleted."
      redirect_to locations_path
    end
    def edit
      @location = Location.find(params[:id])
    end 
    def update
      @location = Location.find(params[:id])

      if @location.update(location_params)
        redirect_to @location
      else
        render :edit
      end
    end
  
    private
    def location_params
        params.require(:location).permit(:name, :street1, :street2, :city, :state, :zip, categories: [])
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @locations = Location.all
  end
  def show
    @location = Location.find(params[:id])
  end
  def new
    @location = Location.new
  end
  def create
    @location = Location.new(location_params)

    if @location.save
      redirect_to @location
    else
      render :new
    end
  end

  private
    def location_params
      params.require(:location).permit(:name, :street1, :street2, :city, :state, :zip)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @locations = Location.all
  end
  def show
    @location = Location.find(params[:id])
  end
  def new
    @location = Location.new
  end
  def create
    @location = Location.new(location_params)

    if @location.save
      redirect_to @location
    else
      render :new
    end
  end

  private
    def location_params
      params.require(:location).permit(:name, :street1, :street2, :city, :state, :zip)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/comments/_form.html.erb
<%= form_with model: [ @location, @location.comments.build ] do |form| %>
    <div class="field mb-3" >
      <%= form.label :comments, class: "form-label" %><br>
      <%= form.text_area :body, class: "form-control" %>
    </div>
    <div class="actions">
      <%= form.submit "Create Comment", class: "btn btn-primary" %>
    </div>
  <% end %>

app/views/favorites/index.html.erb
<%= stylesheet_link_tag "my_style" %>

<div class="container">
<div class="row">
<div class= "col-3">
</div>
<div class= "col-6">


<h1>Favorites!</h1>

<table class="table">
  <tbody>
    <% @favorites.each do |favorite| %>
    <tr class="card border">
      <td>
        <a href="/locations/<%=favorite.location_id %>" >
          <%= favorite.location.name %>
        </a>  
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

</div>

<div class= "col-3">
</div>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= stylesheet_link_tag "my_style" %>
<html>
  <head>
    <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
    <title>WicseProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    
  </head>
  <div id="back">
    <body>
    <div id="nav_style">
    </script>
    <nav class="navbar navbar-expand-lg border navbar-dark" id="myNav">
      <a class="navbar-brand"><%= link_to 'Spot It!', root_path, class: "nav-link", id:'web_name' %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon", id="toggle_hamburger"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item"><%= link_to 'Sites', locations_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to 'Trending', "/trending", class: "nav-link" %></li>
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to 'Profile', edit_user_registration_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to 'Favorites', favorites_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to 'New Location', new_location_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "nav-link" %></li>
          <% else %>
            <li class="nav-item"><%= link_to 'Log In', new_user_session_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </nav>

  <script type="text/javascript">
    $(document).ready(function(){
      setTimeout(function(){
      $('.alert').fadeOut();
      }, 2000);
  })
  </script>
  <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    </div>
      <div id="front">
        <%= yield %>
      </div>
    </body>
  </div>
</html>

app/views/locations/_form.html.erb




<%= form_with model: location do |form| %>
  <div class="field mb-3">
    <%= form.label "Name", class: "form-label" %><br>
    <%= form.text_field :name, class: "form-control" %>
    <% @location.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div class="field mb-3">
    <%= form.label "Street 1", class: "form-label" %><br>
    <%= form.text_area :street1, class: "form-control" %>
    <% @location.errors.full_messages_for(:street1).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div class="field mb-3">
    <%= form.label "Street 2", class: "form-label" %><br>
    <%= form.text_area :street2, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label "City", class: "form-label" %><br>
    <%= form.text_area :city, class: "form-control" %>
    <% @location.errors.full_messages_for(:city).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div class="field mb-3">
    <%= form.label "State", class: "form-label" %><br>
    <%= form.text_area :state, class: "form-control" %>
    <% @location.errors.full_messages_for(:state).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div class="field mb-3">
    <%= form.label "Zip", class: "form-label" %><br>
    <%= form.text_area :zip, class: "form-control" %>
    <% @location.errors.full_messages_for(:zip).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div class="field mb-3 ">
    <%= form.label "Categories", class: "form-label" %><br>
    <%= form.collection_check_boxes(:categories, Location::CATEGORIES, :last, :first ) %>
  </div>

  <div class="actions">
    <%= form.submit button_text, class: "btn btn-primary" %>
  </div>
<% end %>


  

app/views/locations/edit.html.erb
<%= stylesheet_link_tag "my_style" %>
<div class="container">
 <div class="row">
  <div class="col-sm"> 
  </div>

  <div class="col-sm-6 border card">
    <h1>Edit Location</h1>

    <%= render "form", location: @location, button_text: "Edit Location" %>

  </div>

  <div class="col-sm">
  </div>

</div>
</div>

app/views/locations/index.html.erb
<div class="container">
<div class="row">
<div class= "col-3">
</div>
<div class= "col-6">

<h1><%=@title%></h1>


<div id="cats" class="mb-3 form-check form-check-inline">
  <%= form_tag "/locations", method: "GET" do %>
    <%= collection_check_boxes(:location, :categories, Location::CATEGORIES, :last, :first ) do |b| %>
      <% if @cat_checked != nil && @cat_checked.include?(b.value) %>
        <%= b.label(class: "form-check-label") { b.check_box(checked: true, class: "form-check-input") + b.text } %>
      <% else %>
        <%= b.label(class: "form-check-label") { b.check_box(checked: false, class:"form-check-input") + b.text } %>
      <% end %>
    <% end%>
    <br>
    <%= submit_tag 'search', class: "btn btn-primary"%>
  <% end %>
</div>


<div id="loc">
  <%= form_tag "/locations", method: "GET" do %>
    <div class="input-group" id="search_bar">
    <%= text_field_tag :search_by_name, params[:search_by_name], class: "form-control" %>
    <div class="input-group-button">
    <%=button_tag "Search", class: "btn btn-primary" %>
    </div>
    </div>
  <% end %>
</div>

<button id="cats_button" class= "btn btn-secondary">Search by categories</button>
<button id="loc_button" class= "btn btn-secondary">Search by name/zip</button>

<script type="text/javascript">
  var cat_true = <%= @cat_true %>;
  console.log(cat_true);

  if (cat_true) {
    $('#loc').hide();
    $('#cats_button').hide();
  } else{
   $('#cats').hide();
   $('#loc_button').hide();
  }

  $('#cats_button').click(function (){
    $('#cats, #loc').toggle();
    $('#loc_button, #cats_button').toggle();
  });
  $('#loc_button').click(function (){
    $('#cats, #loc').toggle();
    $('#loc_button, #cats_button').toggle();
  });
</script>

<table class="table">
  <tbody>
    <% @locations.each do |location| %>
    <tr class="card border">
      <td>
        <a href="/locations/<%=location.id %>" >
          <%= location.name %>
        </a>  
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class= "col-3">
</div>

</div>
</div>

app/views/locations/new.html.erb
<%= stylesheet_link_tag "my_style" %>
<div class="container">
    <div class="row">
        <div class="col-sm"> 
        </div>

            <div class="col-sm-6 border card">
                <h2>Know a good spot? Tell us about it!</h2>

                <%= render "form", location: @location, button_text: "Add Location" %>
            </div>

        <div class="col-sm">
        </div>

    </div>
</div>

app/views/locations/show.html.erb
<%= stylesheet_link_tag "my_style" %>
<div class="container">
<div class="row">
<div class="col border card"> 


<h1><%= @location.name %></h1>
<h2><%= @location.street1 + ", " + @location.city + ", " + @location.state + " " + @location.zip %></h2>
<% if @location.favorites_count == 0 %>
    <% if user_signed_in? %>
        <%= "Be the First to like this Site!" %><br>
    <% else %>
        <%= "This site does not have any likes yet." %><br>
    <% end %>
<% elsif @location.favorites_count == 1 %>
    <%= @location.favorites_count.to_s + " person liked this location!" %><br>
<% else %>
    <%= @location.favorites_count.to_s + " people liked this location!" %><br>
<% end %>
<% @location.categories.each do |c| %>

<%= c.capitalize %>
<% end %>

<% if user_signed_in? %>
    <div>
        <% @location.user_id %>
        <% if @location.user_id == current_user.id %>
            <%= link_to location_path(@location), method: "delete" do %>
                <span class="iconify" data-icon="bi:trash-fill" data-inline="false"></span>
            <% end %>
            <%= link_to edit_location_path(@location), method: "get" do %>
                <span class="iconify" data-icon="zmdi-edit" data-inline="false"></span>
            <% end %>
        <% else %>
        <% end %>
        <% if @favorite == nil %>
            <%= link_to "/favorites/#{@location.id}", method: "post" do %>
                <span class="iconify" data-icon="carbon:favorite" data-inline="false"></span>
            <% end %>
        <% else %>  
            <%= link_to "/favorites/#{@favorite.id}", method: "delete" do %>
                <span class="iconify" data-icon="carbon:favorite-filled" data-inline="false"></span>
            <% end %>
        <% end %>
    </div>
    <%= render 'comments/form' %>
    
<% end %>
</div>
</div>
</div>

<div class="container">
<div class="row">
<div class="col border card"> 
<h2>Comments</h2>
<% @location.comments.each do |comment| %>
    <div class="col border card"> 
    <% if comment.user %>
    <p>
        <strong>
            <%= comment.user.name%>
        </strong>
    </p>
    <p>
        <%= comment.body %>
    </p>
        <% if user_signed_in? %>
            <% if current_user.id == comment.user_id %>
                <%= link_to "/locations/#{@location.user_id}/comments/#{comment.id}", method: "delete" do %>
                <span class="iconify" data-icon="bi:trash-fill" data-inline="false"></span>
                <% end %>
            <% end %>
        <% end %>
    <% end %>
    </div>
<% end %>
</div>
</div>
</div>

app/views/locations/trending.html.erb
<div class="container">
<div class="row">
<div class= "col-3">
</div>
<div class= "col-6">

<h1><%=@title%></h1>


<div id="cats" class="mb-3 form-check form-check-inline">
  <%= form_tag "/locations", method: "GET" do %>
    <%= collection_check_boxes(:location, :categories, Location::CATEGORIES, :last, :first ) do |b| %>
      <% if @cat_checked != nil && @cat_checked.include?(b.value) %>
        <%= b.label(class: "form-check-label") { b.check_box(checked: true, class: "form-check-input") + b.text } %>
      <% else %>
        <%= b.label(class: "form-check-label") { b.check_box(checked: false, class:"form-check-input") + b.text } %>
      <% end %>
    <% end%>
    <br>
    <%= submit_tag 'search', class: "btn btn-primary"%>
  <% end %>
</div>


<div id="loc">
  <%= form_tag "/locations", method: "GET" do %>
    <div class="input-group" id="search_bar">
    <%= text_field_tag :search_by_name, params[:search_by_name], class: "form-control" %>
    <div class="input-group-button">
    <%=button_tag "Search", class: "btn btn-primary" %>
    </div>
    </div>
  <% end %>
</div>

<button id="cats_button" class= "btn btn-secondary">Search by categories</button>
<button id="loc_button" class= "btn btn-secondary">Search by name/zip</button>

<script type="text/javascript">
  var cat_true = <%= @cat_true %>;
  console.log(cat_true);

  if (cat_true) {
    $('#loc').hide();
    $('#cats_button').hide();
  } else{
   $('#cats').hide();
   $('#loc_button').hide();
  }

  $('#cats_button').click(function (){
    $('#cats, #loc').toggle();
    $('#loc_button, #cats_button').toggle();
  });
  $('#loc_button').click(function (){
    $('#cats, #loc').toggle();
    $('#loc_button, #cats_button').toggle();
  });
</script>

<table class="table">
  <tbody>
    <% @locations.each do |location| %>
    <tr class="card border">
      <td>
        <a href="/locations/<%=location.id %>" >
          <%= location.name %>
        </a>  
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class= "col-3">
</div>

</div>
</div>

app/views/search/index.html.erb
<h1>Search</h1>
<%= form_tag "/locations", method: "GET" do %>
<p>Find me in app/views/search/index.html.erb</p>

app/views/search/new.html.erb
<h1>Know a good spot? Tell us about it!</h1>

<%= form_with model: @location do |form| %>
  <div>
    <%= form.label :Name %><br>
    <%= form.text_field :name %>
    <% @article.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
    <%= form.label :Street 1%><br>
    <%= form.text_area :street1 %>
    <% @article.errors.full_messages_for(:street1).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
    <%= form.label :Street 2%><br>
    <%= form.text_area :street2%>
  </div>

  <div>
    <%= form.label :City%><br>
    <%= form.text_area :city%>
    <% @article.errors.full_messages_for(:city).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
    <%= form.label :State%><br>
    <%= form.text_area :state %>
    <% @article.errors.full_messages_for(:state).each: do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
    <%= form.label :Zip%><br>
    <%= form.text_area :zip%>
    <% @article.errors.full_messages_for(:zip).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>